version: '3.8'

services:
  app:
    build: .
    image: vigneshkumard2797/retail-edge:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: riO8KmmKELcsJSWLzbk6nFBUCaNIuYae
      SPRING_DATASOURCE_URL: postgresql://admin:riO8KmmKELcsJSWLzbk6nFBUCaNIuYae@dpg-ct69qirqf0us738diu50-a.oregon-postgres.render.com/retailedge
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:12.19-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: maxbyte
      POSTGRES_PASSWORD: max2max123456!
      POSTGRES_DB: retail-edge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

volumes:
  postgres_data:
