version: '3.8'

services:
  tomcat:
    build: .
    image: techbee/retail-edge:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_USERNAME: techbee
      SPRING_DATASOURCE_PASSWORD: techBee@retail-Edge@123$%
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/retail-edge
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:12.19-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: techbee
      POSTGRES_PASSWORD: techBee@retail-Edge@123$%
      POSTGRES_DB: retail-edge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: ubuntu/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: ubuntu/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
volumes:
  postgres_data:
